<?php

namespace PNV\CablesBundle\Repositories\View;

use Doctrine\ORM\EntityRepository;

/**
 * TInventaireTronconsErdfView
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TInventaireTronconsErdfView extends EntityRepository
{
}
