<?php

namespace PNV\CablesBundle\Repositories\View;

use Doctrine\ORM\EntityRepository;

/**
 * VueSitesNidification
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VueSitesNidification extends EntityRepository
{
}
