PNV\CablesBundle\Entity\Dico\DicoTypePoteauErdf:
    type: entity
    table: cables73.dico_type_poteau_erdf
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\Dico\DicoTypePoteauErdf
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_type_poteau_erdf
            generator:
                strategy: SEQUENCE
    fields:
        libelle: 
            type: string
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: lib_type_poteau_erdf
    lifecycleCallbacks: {  }
