PNV\CablesBundle\Entity\Dico\DicoSexe:
    type: entity
    table: cables73.dico_sexe
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\Dico\DicoSexe
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_sexe
            generator:
                strategy: SEQUENCE
    fields:
        libelle:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
            column: lib_sexe
    lifecycleCallbacks: {  }
