PNV\CablesBundle\Entity\Dico\DicoCauseMortalite:
    type: entity
    table: cables73.dico_cause_mortalite
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\Dico\DicoCauseMortalite
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_cause_mortalite
            generator:
                strategy: SEQUENCE
    fields:
        libelle:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
            column: lib_cause_mortalite
    lifecycleCallbacks: {  }
