PNV\CablesBundle\Entity\View\OgmCablesRemonteesMecaniques:
    type: entity
    table: cables73.ogm_cables_remontees_mecaniques
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\View\OgmCablesRemonteesMecaniques
    indexes:
        ogm_cables_remontees_mecaniques_index:
            columns:
                - geom
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idcable
            generator:
                strategy: SEQUENCE
    fields:
        geomJson:
            type: json_array
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: geom_json
    lifecycleCallbacks: {  }
