PNV\CablesBundle\Entity\View\TAxesMigratoires:
    type: entity
    table: cables73.t_axes_migratoires
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\View\TAxesMigratoires
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_axe_migratoire
            generator:
                strategy: SEQUENCE
    fields:
        geomJson:
            type: json_array
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: geom_json
    lifecycleCallbacks: {  }