PNV\CablesBundle\Entity\View\OgmTronconsVisualises:
    type: entity
    table: cables73.ogm_troncons_visualises
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\View\OgmTronconsVisualises
    indexes:
        ogm_troncons_visualises_geo_index:
            columns:
                - geom
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idtv
            generator:
                strategy: SEQUENCE
    fields:
        geomJson:
            type: json_array
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: geom_json
    lifecycleCallbacks: {  }
