PNV\CablesBundle\Entity\View\RteLignes:
    type: entity
    table: cables73.rte_lignes
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\View\RteLignes
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_rte_ligne
            generator:
                strategy: SEQUENCE
    fields:
        geomJson:
            type: json_array
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: geom_json
    lifecycleCallbacks: {  }