PNV\CablesBundle\Entity\View\OgmTronconsDangereux:
    type: entity
    table: cables73.ogm_troncons_dangereux
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\View\OgmTronconsDangereux
    indexes:
        ogm_troncons_dangereux_geo_index:
            columns:
                - geom
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idtd
            generator:
                strategy: SEQUENCE
    fields:
        geomJson:
            type: json_array
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: geom_json
    lifecycleCallbacks: {  }
