PNV\CablesBundle\Entity\View\ErdfParafoudre:
    type: entity
    table: cables73.erdf_parafoudre
    schema: cables73
    repositoryClass: PNV\CablesBundle\Repositories\View\ErdfParafoudre
    indexes:
        erdf_parafoudre_index:
            columns:
                - geom
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        geomJson:
            type: json_array
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: geom_json
    lifecycleCallbacks: {  }