<?php

namespace PNV\CablesBundle\Repositories\Edit;

use Doctrine\ORM\EntityRepository;

/**
 * TCasMortalite
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCasMortalite extends EntityRepository
{
}
