<?php

namespace PNV\CablesBundle\Repositories\Edit;

use Doctrine\ORM\EntityRepository;

/**
 * TPhotosPoteauxErdf
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TPhotosPoteauxErdf extends EntityRepository
{
}
