<?php

namespace PNV\CablesBundle\Repositories\Dico;

use Doctrine\ORM\EntityRepository;

/**
 * DicoAge
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DicoAge extends EntityRepository
{
}
