services:
#    commons_users.example:
#        class: Commons\UsersBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    userServ:
        class: Commons\UsersBundle\Services\UserService
        arguments: ["@request_stack"]
